// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVyFsHDxjran0oxCUE4ZaZFNKnHPFmDg',
    appId: '1:1013486873658:web:5a0a694a5e74a320c29903',
    messagingSenderId: '1013486873658',
    projectId: 'loyola-8b679',
    authDomain: 'loyola-8b679.firebaseapp.com',
    storageBucket: 'loyola-8b679.firebasestorage.app',
    measurementId: 'G-0771KEKSJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSS5B5Daanx1CjkIAoxy4bHaLsvsKa5k',
    appId: '1:1013486873658:android:592719c9fc8cfbd7c29903',
    messagingSenderId: '1013486873658',
    projectId: 'loyola-8b679',
    storageBucket: 'loyola-8b679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1t9FUN8hW6hDF8LNdb8fJfYPtDPq65tI',
    appId: '1:1013486873658:ios:eb1d11091a7d0539c29903',
    messagingSenderId: '1013486873658',
    projectId: 'loyola-8b679',
    storageBucket: 'loyola-8b679.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
